### PR TITLE
fix: Update dotnet example to not fail on `AlreadyExistsException` and upgrade TargetFramework to `net6.0`

### LINKED ISSUE #74: Bump .net in example to 6.0
Currently default version and recommended LTS version for .net core is 6.0.

Since I was first time .net user on my current laptop I went and downloaded recommended version and then first time running example I get following error.

Because we pin to version 5 here
https://github.com/momentohq/client-sdk-examples/blob/main/dotnet/MomentoExamples/MomentoApplication/MomentoApplication.csproj#L5

Now that I hit this it seems weird to me we check `.csproj` into repo again. We dont pin to specific version for other client demos do we? I think at minimum we should bump to version 6 over 5 just wanted to bring up maybe longer term revisit this file. Not C# expert though.

```console
➜  MOMENTO_AUTH_TOKEN=*** dotnet run --project MomentoApplication
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.2 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=osx.10.16-x64
  - ```

<img width="1465" alt="Screen Shot 2022-02-28 at 8 03 58 AM" src="https://user-images.githubusercontent.com/5491827/156016456-d0acaf5a-d2f6-41e2-be75-7a8a538c021c.png">
<img width="1002" alt="Screen Shot 2022-02-28 at 8 04 02 AM" src="https://user-images.githubusercontent.com/5491827/156016460-09e3b531-1c0c-4428-ac1b-5971a2aaf450.png">

### LINKED ISSUE #75: .Net example handle cache already exists error
Example should not fail and stop should be consistent with other client examples. Especially since we default to same name `cache` in all our sdk examples so if they have run another example before this will always fail.

```console
➜  MomentoExamples git:(main) ✗ MOMENTO_AUTH_TOKEN=*** dotnet run --project MomentoApplication
Unhandled exception. MomentoSdk.Exceptions.AlreadyExistsException: Status(StatusCode="AlreadyExists", Detail="Cache with name: cache already exists")
   at MomentoSdk.ScsControlClient.CreateCache(String cacheName)
   at MomentoSdk.Responses.SimpleCacheClient.CreateCache(String cacheName)
   at MomentoApplication.Program.Main(String[] args) in /Users/eaw/dev/momento/client-sdk-examples/dotnet/MomentoExamples/MomentoApplication/Program.cs:line 18
```

### PR DESCRIPTION
**Pull request by poppoerika**
- Updated the dotnet example so that it won't fail when cache already exists
- Upgraded TargetFramework to `net6.0` to align with their recommended .NET version

Closes #74 
Closes #75

### CODE REVIEW

File: dotnet/MomentoExamples/MomentoApplication/Program.cs [hunk 1]
```diff
@@ -15,7 +15,14 @@ class Program
         static void Main(string[] args)
         {
             using SimpleCacheClient client = new SimpleCacheClient(MOMENTO_AUTH_TOKEN, DEFAULT_TTL_SECONDS);
-            client.CreateCache(CACHE_NAME);
+            try
+            {
+                client.CreateCache(CACHE_NAME);
+            }
+            catch (AlreadyExistsException e)
```
Comment (gautamomento) [inline dotnet/MomentoExamples/MomentoApplication/Program.cs:22]: LGTM. But can you see if .NET supports catching exception withoput using the variable?

```
try {
client.CreateCache(CACHE_NAME);
} catch (AlreadyExistsException) {
// print
}
```

Comment (poppoerika) [reply dotnet/MomentoExamples/MomentoApplication/Program.cs:22]: It does. I'll remove the variable.

**Review by eaddingtonwhite — APPROVED** [review]
🚢

File: dotnet/README.md [hunk 2]
```diff
@@ -13,11 +15,13 @@ MOMENTO_AUTH_TOKEN=<YOUR AUTH TOKEN> dotnet run --project MomentoApplication
 Example Code: [MomentoApplication](MomentoExamples/MomentoApplication/Program.cs)
 
 ## Using the .NET SDK in your project
-SDK is built for target framework [.NET Standard 2.1 ](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.1.md)
+
+SDK is built for target framework [.NET Standard 2.1](https://github.com/dotnet/standard/blob/v2.1.0/docs/versions/netstandard2.1.md)
```
Comment (danielamiao) [inline dotnet/README.md:19]: should this for target framework 6.0 now?

Comment (poppoerika) [reply dotnet/README.md:19]: @danielamiao - .NET Standard version 2.1 supports .NET and .NET Core version 6.0 which I believe what we updated in this pr. So no need to change the standard version.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1

image

Comment (danielamiao) [reply dotnet/README.md:19]: great thanks for checking, i got confused with all the version numbers
